/**
 * ResearchPage's research package: the domain, the real discovery and read
 * paths, the evidence rules, the report renderer and the PDF export — plus the
 * plugin that exposes them to the agent as tools.
 */

export type {
  ActionDelta,
  AssessmentDirectness,
  AssessmentRelationship,
  ActivityLevel,
  BriefFieldName,
  BriefFieldState,
  BriefFieldStates,
  CellRef,
  CellStatus,
  ClaimBasis,
  ClaimConditions,
  ClaimType,
  Comparability,
  CostStage,
  Dimension,
  DiscoveryTelemetry,
  EditActionOutcome,
  Evidence,
  ExportArtifact,
  MatrixCell,
  MechanismStep,
  Paragraph,
  QualityCheckRecord,
  ReadScope,
  ReadSnapshot,
  ReadStatus,
  Report,
  ReportBlock,
  ReportClaim,
  ReportDraftState,
  ReportFrame,
  ReportGenerationFailure,
  ReportGenerationState,
  ReportGapNote,
  ReportReviewFlag,
  ReportSection,
  ReportTask,
  ReportValidation,
  ResearchActionOutcome,
  ResearchActivityEvent,
  ResearchActivityKind,
  ResearchAttempt,
  ResearchBudget,
  ResearchGapNote,
  ResearchProgressStage,
  ResearchResolution,
  ResearchResolutionStatus,
  ResearchRunRecord,
  ResearchSection,
  ResearchStage,
  ResearchUsage,
  RunOutcome,
  Source,
  SourceRole,
  Subject,
  SupportAssessment,
  TaskStatus,
} from "./domain.js";
export {
  DEFAULT_BUDGET,
  BRIEF_FIELDS,
  deriveCellCoverage,
  EMPTY_ACTION_DELTA,
  emptyUsage,
  ID_PREFIX,
  isCellRef,
  isCovered,
  lockedFieldStates,
  needsAttention,
  PRIMARY_ROLES,
  suggestedFieldStates,
} from "./domain.js";

export {
  BLUEPRINT_ID_V1,
  BLUEPRINT_ID_V2,
  BLUEPRINTS,
  blueprintById,
  blueprintSections,
  requiredSectionsOf,
  sectionObligation,
  sectionSpecOf,
  TECHNICAL_COMPARISON_V2,
  V2_COMPARISON_DIMENSIONS,
  type BlueprintSpec,
  type ClaimRequirement,
  type CognitiveComponent,
  type DepthLevel,
  type QualityRule,
  type SectionSpec,
} from "./blueprint.js";

export {
  adequacyNeedsAttention,
  assertsRanking,
  comparabilityLabel,
  costFamiliesOf,
  deriveClaimAdequacy,
  validateClaimContract,
  type AdequacyState,
  type ClaimAdequacy,
  type ClaimContext,
  type ClaimVerdict,
} from "./claims.js";

export {
  BLANK_CELL_REMEDY,
  blankCellLabel,
  blankCellsOfTable,
  tableGapsOf,
  validateArtifactQuality,
  type ArtifactDraft,
  type ArtifactInput,
  type ArtifactVerdict,
  type BlankCell,
  type TableGap,
} from "./artifact.js";

export {
  CELL_STATE_WORDS,
  deriveResearchResolution,
  newMaterialSentence,
  proposalFailureCopy,
  proposalRepairCopy,
  RESOLUTION_LABELS,
  type ResolutionCell,
  type ResolutionInput,
} from "./outcome.js";

export { canonicalJson, hashOf } from "./hash.js";

export {
  applyBriefPatch,
  briefBlueprintOf,
  briefFieldHash,
  briefFieldStatesOf,
  briefFieldSummary,
  briefFieldValue,
  briefHashOf,
  briefStructureView,
  briefVersionOf,
  briefWithApplication,
  EDITABLE_BRIEF_FIELDS,
  fieldTakesFreeText,
  GUIDE_LEAD_IN_LIMIT,
  GUIDE_MAX_DECISIONS,
  GUIDE_MIN_DECISIONS,
  guideAnswerLabelsOf,
  guideAnswerTextOf,
  guideLeadInOf,
  guideQuestionIsStale,
  guideReadinessDecisions,
  INITIAL_BRIEF_VERSION,
  isStructural,
  MAX_BRIEF_DIMENSIONS,
  MAX_BRIEF_FOCUS,
  MAX_BRIEF_SUBJECTS,
  nextGuideTarget,
  patchFromFreeText,
  readBriefPatch,
  STRUCTURAL_BRIEF_FIELDS,
  validateBriefDraft,
  type BriefApplication,
  type BriefApplyResult,
  type BriefDimensionInput,
  type BriefPatch,
  type BriefPatchProblem,
  type BriefPatchReading,
  type BriefSubjectInput,
  type BriefValidation,
  type GuideAnswerRecord,
  type GuideOption,
  type GuideQuestion,
  type GuideQuestionStatus,
  type GuideTarget,
} from "./brief.js";

export {
  capabilitiesFor,
  classifyIntent,
  createGrant,
  EMPTY_ACTION_USAGE,
  EDIT_RESEARCH_BUDGET,
  grantHasCapability,
  USER_RESEARCH_BUDGET,
  type ActionCapability,
  type ActionGrant,
  type ActionIntent,
  type ActionUsage,
  type AssistantIntent,
  type GrantBudget,
  type GrantInput,
  type GrantOrigin,
  type GrantTargetType,
  type IntentReading,
} from "./semantics.js";

export {
  applyProposal,
  checkProposalFreshness,
  contentOf,
  createProposal,
  sectionHash,
  type Proposal,
  type ProposalBase,
  type ProposalSection,
  type ProposalStatus,
  type ProposalTarget,
} from "./proposal.js";

export {
  blockText,
  buildRevisionBundle,
  DEFAULT_THEME_ID,
  isFrozenRevision,
  RENDERER,
  reportContentOf,
  type FrozenEvidenceRef,
  type FrozenFrame,
  type FrozenGap,
  type FrozenRevision,
  type FrozenSourceRef,
  type RevisionBundleInput,
} from "./revision.js";

export { openResearchRepository, newId, type ResearchRepository } from "./repository.js";

export {
  attemptArxiv,
  attemptWithProvider,
  arxivIdOf,
  arxivIdOfDoi,
  buildArxivQuery,
  candidateKeys,
  classifyStatus,
  classifyThrown,
  dedupeCandidates,
  DEFAULT_DISCOVERY_BUDGET_MS,
  DEFAULT_RETRY_POLICY,
  normalizeArxivId,
  normalizeDoi,
  normalizeUrl,
  parseArxivFeed,
  PROVIDER_INTERVALS,
  PROVIDER_NAMES,
  queryLadder,
  queryTerms,
  rateLimitedFor,
  requestWithRetries,
  retryAfterMsOf,
  retryDecisionOf,
  searchArxiv,
  SearchError,
  sleepWithSignal,
  type AttemptResult,
  type DiscoveryEvent,
  type DiscoveryEventKind,
  type FetchLike,
  type ResearchProvider,
  type RetryPolicy,
  type SearchAttempt,
  type SearchCandidate,
  type SearchFailureKind,
  type SearchOptions,
  type SearchOutcome,
  type SleepLike,
} from "./search.js";

export {
  abstractFromInvertedIndex,
  candidateOfOpenAlexWork,
  openAlexIdOf,
  parseOpenAlexWorks,
  searchOpenAlex,
} from "./openalex.js";

export {
  ProviderCircuitBreaker,
  searchSources,
  type DiscoveryOptions,
  type ProviderCircuitState,
  type ProviderSearch,
} from "./discovery.js";

export { readSource, type ReadMetadata, type ReadOutcome, type ReadRequest, type ReaderOptions } from "./read.js";
export { decodeEntities, extractHtmlDocument, extractPlainText, MAX_DOCUMENT_CHARS, metaContent } from "./html.js";
export {
  ABSTRACT_META_NAMES,
  isAbstractHeading,
  isArticleBodyHeading,
  isNonArticleHeading,
  MIN_ABSTRACT_CHARS,
  MIN_BODY_CHARS,
  MIN_BODY_OVER_ABSTRACT,
  MIN_BODY_PARAGRAPHS,
  MIN_BODY_SECTIONS,
  normaliseHeading,
  pageAbstractOf,
  recogniseArticleBody,
  type ArticleBody,
  type BodyRecognitionOptions,
  type PageAbstract,
} from "./article.js";

export {
  draftEvidence,
  MAX_EXCERPT_CHARS,
  pickParagraphs,
  scopeLabel,
  tokenize,
  verifyEvidenceText,
  type EvidenceCheck,
} from "./evidence.js";

export {
  createTask,
  DEFAULT_DIMENSIONS,
  normalizeCard,
  outlineOf,
  slugId,
  STRUCTURE_ID,
  STRUCTURE_SECTIONS,
  taskOfSession,
  type NormalizedCard,
  type ProposedCard,
} from "./structure.js";

export {
  buildCitations,
  evidenceUsedBy,
  gapNotesOf,
  locatorLabel,
  missingCells,
  reportContentHash,
  sealReport,
  validateReport,
  type CitationEvidence,
  type Citations,
  type CitationSource,
  type ReportDraft,
  type ValidationResult,
} from "./report.js";

export { escapeHtml, renderReportHtml, renderRevisionHtml, REPORT_CSS, type RenderInput } from "./render.js";
export { exportHtmlToPdf, findPdfBrowser, type PdfExportOptions, type PdfExportResult } from "./pdf.js";

export {
  createResearchService,
  SECTION_IDS,
  type AcceptProposalResult,
  type ActionBudgetView,
  type AssessResult,
  type BriefConflict,
  type BudgetScope,
  type BriefView,
  type CellView,
  type ConfirmResult,
  type DocumentContext,
  type DocumentScopeDeclaration,
  type DocumentUploadInput,
  type DocumentUploadResult,
  type GuideAnswerInput,
  type GuideAnswerResult,
  type GuideDecisionView,
  type GuideOptionView,
  type GuideQuestionView,
  type GuideTargetDecision,
  type IntentConfirmResult,
  type IntentConflict,
  type IntentDirectionResult,
  type DocumentAccessRef,
  type IntentMessageResult,
  type IntentResult,
  type IntentTurnResult,
  type PatchBriefResult,
  type ProposeGuideQuestionResult,
  type ReadResult,
  type Refusal,
  type ResearchService,
  type ResearchServiceOptions,
  type SaveReportResult,
  type SearchResult,
  type WorkspaceState,
} from "./service.js";

export { boundedJson, createResearchTools, MAX_TOOL_RESULT_CHARS, type ResearchTools } from "./tools.js";
export { createResearchPlugin, createResearchToolSet, type ResearchPlugin } from "./plugin.js";
export { RESEARCH_SYSTEM_PROMPT, researchTaskBrief } from "./prompt.js";

export {
  DIRECTION_CONFIRM_QUESTION,
  INTENT_STATUS_LABELS,
  INTENT_VIEW_TURNS,
  MAX_DIRECTION_DIMENSIONS,
  MAX_DIRECTION_FOCUS,
  MAX_DIRECTION_SUBJECTS,
  MAX_INTENT_DECISIONS,
  MAX_INTENT_MESSAGE_CHARS,
  MAX_INTENT_OPTION_CHARS,
  MAX_INTENT_OPTIONS,
  MAX_INTENT_QUESTION_CHARS,
  MAX_INTENT_SUMMARY_CHARS,
  MAX_INTENT_TURNS,
  asksForDirection,
  confirmedBriefFacts,
  createIntentDraft,
  directionSummaryLine,
  fieldsLeftOpen,
  intentViewOf,
  lastUserMessage,
  readDirection,
  readIntentMessage,
  readIntentQuestion,
  type ConfirmedBriefFacts,
  type DirectionDimension,
  type DirectionSubject,
  type IntentDecision,
  type IntentDraft,
  type IntentStatus,
  type IntentTurn,
  type IntentView,
  type ResearchDirection,
} from "./intent.js";

export {
  DOCUMENT_EXTENSIONS,
  MAX_DOCUMENTS_PER_SESSION,
  MAX_DOCUMENT_BYTES,
  MAX_DOCUMENT_EXCERPT_CHARS,
  MAX_DOCUMENT_FILENAME_CHARS,
  MAX_DOCUMENT_FRAGMENTS,
  MAX_DOCUMENT_HEADING_CHARS,
  MAX_DOCUMENT_OUTLINE_CHARS,
  MAX_DOCUMENT_PREVIEW_CHARS,
  MAX_PARSED_CHARS,
  UNTRUSTED_DOCUMENT_NOTE,
  boundedOutline,
  documentPreview,
  documentSummaryLine,
  documentViewOf,
  isDocumentUsage,
  markdownNameFor,
  outlineEntryChars,
  outlineNote,
  pageOfChar,
  parseDocument,
  readConversionRecord,
  readDocument,
  readDocumentContent,
  readDocumentFilename,
  type ConversionTrust,
  type DocumentConversion,
  type DocumentConversionInput,
  type DocumentConversionReading,
  type DocumentFragment,
  type DocumentHeading,
  type DocumentOrigin,
  type DocumentOutlineReading,
  type DocumentPageSpan,
  type DocumentPreview,
  type DocumentReadRequest,
  type DocumentReadResult,
  type DocumentUsage,
  type DocumentView,
  type ParsedDocument,
  type StoredDocument,
} from "./documents.js";
